name: Pack to release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Chrome Webstore Upload CLI
        run: npm install -g crx

      - name: Install pnpm
        run: npm install -g pnpm@8.15.7

      - name: Install dependencies
        run: pnpm install

      - name: Build Chrome Extension
        run: pnpm build

      - name: Write PEM file
        run: echo "${{secrets.EXTENSION_PEM_KEY}}" > extension.pem

      - name: Pack Chrome Extension
        run: |
          cd dist
          npx crx pack -p ../key.pem -o extension.crx .
          mv extension.crx $GITHUB_WORKSPACE

      - name: Upload CRX to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/extension.crx
          asset_name: extension.crx
          asset_content_type: application/x-chrome-extension
          token: ${{ secrets.REPO_TOKEN }}
