name: Pack Chrome Extension and Add to Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install Chrome Webstore Upload CLI
        run: npm install -g chrome-webstore-upload-cli

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Chrome Extension
        run: pnpm build

      - name: Write PEM file
        run: echo "${{secrets.EXTENSION_PEM_KEY}}" > extension.pem

      - name: Pack Chrome Extension
        run: |
          cd dist
          zip -r extension.zip .
          crx pack extension.zip --key ../extension.pem
          mv extension.crx $GITHUB_WORKSPACE

      - name: Upload CRX to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/extension.crx
          asset_name: extension.crx
          asset_content_type: application/x-chrome-extension
          token: ${{ secrets.GITHUB_TOKEN }}
